### ISSUE TITLE
[Suggestion] anyway to detect gamma levels to block full bright?

### ISSUE THREAD

**Issue by Whiskah** [LoneDev6/Issues-Wraith#37]
I know full bright can be detected when it's a mod but is there a way to detect if their gamma level is set above 1.0? If so kick etc (Can be set manually in settings.txt to achieve fullbright)

**Comment by LoneDev6** [comment]
I really doubt since this info is not send to the server.
A solution would be to kick the player if they're mining without placing lights for too long, but this is not a solution, some people may have visual problems and that's why they use fullbright.
Also note that modern MC has an increased base light level: https://www.spigotmc.org/resources/darkernights.87814/



Do you have any other idea?
